spring.application.name=PresentationLayer
server.port=9090
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.username=Vishal
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
